/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new PlayerText:backBox[MAX_PLAYERS];
new PlayerText:playerMoney[MAX_PLAYERS];
new PlayerText:playerArmour[MAX_PLAYERS];
new PlayerText:playerChar[MAX_PLAYERS];

public OnFilterScriptInit()
{
    return 1;
}

public OnFilterScriptExit()
{
    return 1;
}

public OnPlayerConnect(playerid)
{
    backBox[playerid] = CreatePlayerTextDraw(playerid, 577.000000, 6.000000, "_");
    PlayerTextDrawFont(playerid, backBox[playerid], 1);
    PlayerTextDrawLetterSize(playerid, backBox[playerid], 0.600000, 10.300003);
    PlayerTextDrawTextSize(playerid, backBox[playerid], 300.500000, 84.500000);
    PlayerTextDrawSetOutline(playerid, backBox[playerid], 1);
    PlayerTextDrawSetShadow(playerid, backBox[playerid], 0);
    PlayerTextDrawAlignment(playerid, backBox[playerid], 2);
    PlayerTextDrawColour(playerid, backBox[playerid], -1);
    PlayerTextDrawBackgroundColour(playerid, backBox[playerid], 255);
    PlayerTextDrawBoxColour(playerid, backBox[playerid], 1296911871);
    PlayerTextDrawUseBox(playerid, backBox[playerid], 1);
    PlayerTextDrawSetProportional(playerid, backBox[playerid], 1);
    PlayerTextDrawSetSelectable(playerid, backBox[playerid], 0);

    playerMoney[playerid] = CreatePlayerTextDraw(playerid, 549.000000, 76.000000, "$00000000");
    PlayerTextDrawFont(playerid, playerMoney[playerid], 3);
    PlayerTextDrawLetterSize(playerid, playerMoney[playerid], 0.279166, 1.399999);
    PlayerTextDrawTextSize(playerid, playerMoney[playerid], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, playerMoney[playerid], 2);
    PlayerTextDrawSetShadow(playerid, playerMoney[playerid], 0);
    PlayerTextDrawAlignment(playerid, playerMoney[playerid], 1);
    PlayerTextDrawColour(playerid, playerMoney[playerid], -1061109505);
    PlayerTextDrawBackgroundColour(playerid, playerMoney[playerid], 255);
    PlayerTextDrawBoxColour(playerid, playerMoney[playerid], 50);
    PlayerTextDrawUseBox(playerid, playerMoney[playerid], 0);
    PlayerTextDrawSetProportional(playerid, playerMoney[playerid], 1);
    PlayerTextDrawSetSelectable(playerid, playerMoney[playerid], 0);

    playerArmour[playerid] = CreatePlayerTextDraw(playerid, 578.000000, 57.000000, "100");
    PlayerTextDrawFont(playerid, playerArmour[playerid], 2);
    PlayerTextDrawLetterSize(playerid, playerArmour[playerid], 0.241666, 0.899999);
    PlayerTextDrawTextSize(playerid, playerArmour[playerid], 400.000000, 17.000000);
    PlayerTextDrawSetOutline(playerid, playerArmour[playerid], 1);
    PlayerTextDrawSetShadow(playerid, playerArmour[playerid], 0);
    PlayerTextDrawAlignment(playerid, playerArmour[playerid], 2);
    PlayerTextDrawColour(playerid, playerArmour[playerid], -1);
    PlayerTextDrawBackgroundColour(playerid, playerArmour[playerid], 255);
    PlayerTextDrawBoxColour(playerid, playerArmour[playerid], 50);
    PlayerTextDrawUseBox(playerid, playerArmour[playerid], 0);
    PlayerTextDrawSetProportional(playerid, playerArmour[playerid], 1);
    PlayerTextDrawSetSelectable(playerid, playerArmour[playerid], 0);

    playerChar[playerid] = CreatePlayerTextDraw(playerid, 552.000000, 8.000000, "Preview_Model");
    PlayerTextDrawFont(playerid, playerChar[playerid], 5);
    PlayerTextDrawLetterSize(playerid, playerChar[playerid], 0.600000, 2.000000);
    PlayerTextDrawTextSize(playerid, playerChar[playerid], 50.000000, 43.000000);
    PlayerTextDrawSetOutline(playerid, playerChar[playerid], 0);
    PlayerTextDrawSetShadow(playerid, playerChar[playerid], 0);
    PlayerTextDrawAlignment(playerid, playerChar[playerid], 1);
    PlayerTextDrawColour(playerid, playerChar[playerid], -1);
    PlayerTextDrawBackgroundColour(playerid, playerChar[playerid], 1296911871);
    PlayerTextDrawBoxColour(playerid, playerChar[playerid], 1296911871);
    PlayerTextDrawUseBox(playerid, playerChar[playerid], 0);
    PlayerTextDrawSetProportional(playerid, playerChar[playerid], 1);
    PlayerTextDrawSetSelectable(playerid, playerChar[playerid], 0);
    PlayerTextDrawSetPreviewModel(playerid, playerChar[playerid], 24);
    PlayerTextDrawSetPreviewRot(playerid, playerChar[playerid], -10.000000, 0.000000, -20.000000, 1.000000);
    PlayerTextDrawSetPreviewVehColours(playerid, playerChar[playerid], 1, 1);

    return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
    PlayerTextDrawDestroy(playerid, backBox[playerid]);
    PlayerTextDrawDestroy(playerid, playerMoney[playerid]);
    PlayerTextDrawDestroy(playerid, playerArmour[playerid]);
    PlayerTextDrawDestroy(playerid, playerChar[playerid]);
    return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
    if (!strcmp(cmdtext, "/tdtest", true))
    {
        PlayerTextDrawShow(playerid, backBox[playerid]);
        PlayerTextDrawShow(playerid, playerMoney[playerid]);
        PlayerTextDrawShow(playerid, playerArmour[playerid]);
        PlayerTextDrawShow(playerid, playerChar[playerid]);
        return 1;
    }
    return 0;
}
